name = input("Enter your full name: ")
phone_num = input("Enter your phone number: ")

result1 = len(name)
result2 = name.find(" ")
result3 = name.find("B")
result4 = name.rfind("a")
result5 = name.rfind("q")
#name = name.capitalize()
#name = name.upper()
name = name.lower()
result6 = name.isdigit()
result7 = name.isalpha()
count_spaces = phone_num.count(" ")
replace_spaces = phone_num.replace(" ", "-")

print(result1)
print(result2)
print(result3)
print(result4)
print(result5)
print(result6)
print(result7)
print(count_spaces)
print(replace_spaces)
print(name)

print(help(str))